server:
  port: 9001
#  port: 0

spring:
  application:
    name: service-a1
  cloud:
    config:
      uri:
      - http://localhost:8888    
        
management:
  endpoints:
    web:
      exposure:
       include: "*"
#      include: hystrix.stream
                
eureka:         
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2       
            
#logging:
#  level:
#    employee:
#      service: DEBUG
